#!/usr/bin/env node

// Update schema.json with locale strings from zotero.properties for the types and fields defined
// in schema.json
//
// This is generally run automatically by locale/run from the zotero-build repo.
//
// To add a new type or field, add it to schema.json, add the English string to zotero.properties,
// and run locale/run, which merges English strings, pulls translations from Transifex, and runs
// this script.

const path = require('path');
const fs = require('fs');

async function run() {
	var clientDir = path.join(__dirname, '..', '..', '..', '..');
	if (!fs.existsSync(path.join(clientDir, 'chrome'))) {
		console.error(`Not within a Zotero client directory`);
		process.exitCode = 1;
		return;
	}
	
	var oldJSON = fs.readFileSync('schema.json').toString();
	var data = JSON.parse(oldJSON);
	var version = parseInt(data.version);
	
	// Sort item types
	data.itemTypes.sort((a, b) => {
		return a.itemType.localeCompare(b.itemType);
	});
	
	// Regenerate localized strings using the files in chrome/locale
	data.locales = {};
	var itemTypes = data.itemTypes.map(x => x.itemType);
	var fields = Array.from(
		new Set(
			data.itemTypes.map(x => x.fields).reduce(
				(accumulator, currentValue) => {
					return accumulator.concat(currentValue.map(x => x.field));
				},
				[
					'itemType',
					// Base or primary fields used as search conditions
					'authority',
					'medium',
					'number',
					'dateAdded',
					'dateModified'
				]
			)
		)
	);
	var creatorTypes = Array.from(new Set(data.itemTypes.map(x => x.creatorTypes).reduce((accumulator, currentValue) => {
		return accumulator.concat(currentValue.map(x => x.creatorType));
	}, [])));
	var cmp = (a, b) => {
		return a.localeCompare(b, 'en', { sensitivity: 'base' });
	};
	itemTypes.sort(cmp);
	fields.sort(cmp);
	creatorTypes.sort(cmp);
	
	// Read in en-US schema.ftl file for newer strings
	let englishProps = fs.readFileSync(
		path.join(clientDir, 'chrome', 'locale', 'en-US', 'zotero', 'schema.ftl')
	);
	let englishLines = englishProps.toString().split(/\n/g);
	let englishStrings = new Map();
	for (let line of englishLines) {
		if (!/^[^-].+\s*=\s*.+/.test(line)) continue;
		let [ key, str ] = line.split(/\s*=\s*/);
		if (!key) continue;
		
		// Change to use period separator like zotero.properties
		key = key.replace('-', '.')
		
		englishStrings.set(key, str);
	}
	
	var dirs = fs.readdirSync(path.join(clientDir, 'chrome', 'locale'));
	for (let locale of dirs) {
		if (!/^[a-z]{2}(-[A-Z]{2})?/.test(locale)) {
			continue;
		}
		
		data.locales[locale] = {
			itemTypes: {},
			fields: {},
			creatorTypes: {}
		};
		
		// Read in zotero.properties file for locale
		let props = fs.readFileSync(
			path.join(clientDir, 'chrome', 'locale', locale, 'zotero', 'zotero.properties')
		);
		let lines = props.toString().split(/\n/g);
		let strings = new Map(englishStrings);
		for (let line of lines) {
			let [ key, str ] = line.split(/\s*=\s*/);
			if (!key) continue;
			strings.set(key, str);
		}
		
		// Read in schema.ftl file (newer strings)
		try {
			props = fs.readFileSync(
				path.join(clientDir, 'chrome', 'locale', locale, 'zotero', 'schema.ftl')
			);
		}
		catch (e) {
			console.log(`schema.ftl not found for ${locale} -- using English strings`);
			props = "";
		}
		lines = props.toString().split(/\n/g);
		for (let line of lines) {
			if (!/^[^-].+\s*=\s*.+/.test(line)) continue;
			let [ key, str ] = line.split(/\s*=\s*/);
			if (!key) continue;
			
			// Change to use period separator like zotero.properties
			key = key.replace('-', '.')
			
			strings.set(key, str);
		}
		
		data.locales[locale].itemTypes = getLocalizedStrings(locale, strings, 'itemTypes', itemTypes);
		data.locales[locale].fields = getLocalizedStrings(locale, strings, 'itemFields', fields);
		data.locales[locale].creatorTypes = getLocalizedStrings(locale, strings, 'creatorTypes', creatorTypes);
	}
	
	// Write new file with incremented version
	var newJSON = JSON.stringify(data, null, '\t') + "\n";
	if (oldJSON != newJSON) {
		console.log("Schema updated");
		fs.writeFileSync('schema.json', newJSON);
	}
	else {
		console.log("Schema hasn't changed");
	}
}

function getLocalizedStrings(locale, strings, prefix, subjects) {
	var data = {};
	for (let subject of subjects) {
		let key = prefix + '.' + subject;
		let value;
		
		// Use hard-coded versions of identifiers that shouldn't be localized
		switch (subject) {
			case 'arXivID':
				value = 'arXiv ID';
				break;
			
			case 'DOI':
			case 'ISBN':
			case 'ISSN':
			case 'PMID':
			case 'PMCID':
				value = subject;
				break;
			
			default:
				value = strings.get(key);
		}
		
		if (!value) {
			// 'type' is only a base field, so it doesn't have a string
			if (key == 'itemFields.type') {
				continue;
			}
			throw new Error(`Localized string ${key} missing for ${locale}. `
				+ "Did you update the en-US zotero.properties with new types and fields "
				+ "and merge the new English strings?\n");
		}
		data[subject] = value;
	}
	return data;
}

(async function () {
	try {
		await run();
	}
	catch (e) {
		console.error(e);
	}
})();
